language: generic
os:
  - linux

dist: trusty

services:
  - docker

env:
  - ARCH=x86_64

matrix:
  include:
    - env: TILEDB_IMG="release"

    - env: TILEDB_IMG="dev"

    - env:
        - USE_S3="ON"
        - TILEDB_IMG="release"

install:
  - docker build -t tiledb:base base

  - if [[ "$USE_S3" == "ON" ]]; then
      docker build --build-arg enable=s3 -t tiledb:${TILEDB_IMG} ${TILEDB_IMG};
    else
      docker build -t tiledb:${TILEDB_IMG} ${TILEDB_IMG};
    fi

script:
  - docker run tiledb:${TILEDB_IMG}
